# Dependencies
markdown: kramdown
highlighter: rouge

author:
  name: 'Saul Reynolds-Haertle'
  url: 'keybase.io/saulrh'

title: Saul Reynolds-Haertle
email: saul+blogabout@saulrh.com
description: >- # this means to ignore newlines until "baseurl:"

  Programmer and creative builder-of-things. Calling up that which I
  cannot put down on a biweekly basis!

paginate: 15

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jemoji

sidebar_home_link:  true

comments: false
