# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
title: Saul Reynolds-Haertle
tagline: My personal website and blog
description: >-
  Personal website for Saul Reynolds-Haertle, arcane programmer -
  calling up that which I cannot put down a specialty! - and
  creative builder-of-things.
url: "www.saulrh.com"
baseurl: /
repository: "saulrh/saulrh.github.io"

author:
  name: 'Saul Reynolds-Haertle'
  url: 'keybase.io/saulrh'

paginate: 15

github:
  repo: https://github.com/saulrh/saulrh.github.io
